---
- name: Insert MySQL root password to debconf configuration
  debconf:
    name: 'mysql-server'
    question: "{{ item }}"
    value: '{{ MYSQL_ROOT_PASS | quote }}'
    vtype: 'password'
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again

- name: Install datastore MySQL
  apt: pkg=mysql-server state=present
  when: IS_DATASTORE_MYSQL

- name: Install talo MySQL user
  mysql_user: 
    login_user=root 
    login_password="{{ MYSQL_ROOT_PASS }}"
    name=talo 
    password=xxpassxx 
    priv=*.*:ALL,GRANT
    state=present

- name: Create talo MySQL database
  mysql_db: 
    login_user=root
    login_password="{{ MYSQL_ROOT_PASS }}"
    name=talo state=present

- name: Add MySQL datastore to taloLogger.conf
  lineinfile:
    dest=/etc/mysql/my.cnf
    regexp='^bind-address'
    line='bind-address=0.0.0.0'
  when: db_only
